version: '3.8'

services:
  app:
    container_name: timetable_app
    build:
      context: ./app
      dockerfile: .docker/Dockerfile
    restart: always
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app

  api:
    container_name: timetable_api
    build:
      context: ./api
      dockerfile: .docker/Dockerfile
    restart: always
    env_file: .env
    ports:
      - 4000:3000
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: timetable_db
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: timetable-pgadmin4
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

networks:
  tt-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
